version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      - cron: "*/5 * * * *"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      - cron: "*/5 * * * *"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    labels:
      - "dependencies"
